language: go

before_script:
  - go get -u golang.org/x/tools/cmd/vet
  - go get -u github.com/golang/lint/golint

go: 1.5

script:
  - go build -v ./...
  - go test -v ./...
  - golint ./..
  - go vet ./...
